name = "revanced-api"
main = "src/index.ts"
compatibility_date = "2025-02-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "data"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "revanced-api"
database_id = "bb857b8a-95ba-45e4-8517-df0a7645957a"
migrations_dir = "drizzle/migrations"
[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
[vars]
ALLOWED_ORIGINS = "*"
ENVIRONMENT = "production"

[vars]
ALLOWED_ORIGINS = "*"
ENVIRONMENT = "production"
GITHUB_ORGANIZATIONS = "ReVanced"
GITHUB_TOKEN = "dummy_token"
