name = "revanced-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "revanced-api"
database_name = "revanced-api"
database_id = "revanced-api"

[vars]
ALLOWED_ORIGINS = "*"
ENVIRONMENT = "production"
GITHUB_ORGANIZATIONS = "ReVanced"
GITHUB_TOKEN = "dummy_token"

[env.production.vars]
ALLOWED_ORIGINS = "*"
ENVIRONMENT = "production"
GITHUB_ORGANIZATIONS = "ReVanced"
GITHUB_TOKEN = "dummy_token"

[observability]
enabled = true

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true
