name: Deploy API to Cloudflare Workers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Create about.json & Deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          JSON_CONTENT='{"version":"1.0.0","commit":{"sha":"0000000","message":"Initial build","date":"2026-01-01"}}'
          echo "$JSON_CONTENT" > about.json
          echo "$JSON_CONTENT" > src/about.json
          bun run db:migration:apply --remote
          bun run deploy
